pipeline:
  build:
    when:
      event: push
    image: fhautomateddev/library-ci-tools
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 -u /scripts/images/build.py
      
  spectests:
    when:
      event: push
    image: 1and1internet/ubuntu-16-rspec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export IMAGE=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}
      - echo ${IMAGE}
      - rspec -f documentation tests/serverspec.rb
      
  publish:
    when:
      event: push
    image: fhautomateddev/library-ci-tools
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_STORAGE_PATH}:/tmp/image-comparison
    secrets: [ DOCKERHUB_USERNAME, DOCKERHUB_PASSWORD, DOCKERHUB_EMAIL, BUILD_TRIGGER_API_URL, BUILD_TRIGGER_API_USERNAME, BUILD_TRIGGER_API_PASSWORD, DEPENDENCY_GRAPH_URL, DEPENDENCY_GRAPH_USERNAME, DEPENDENCY_GRAPH_PASSWORD, TEMPLATE_UPDATER_URL, TEMPLATE_UPDATER_USERNAME, TEMPLATE_UPDATER_PASSWORD, host_storage_path ]
    commands:
     - export SHARED_BUILD_STORAGE=$HOST_STORAGE_PATH
     - python3 -u /scripts/images/publish.py
