build:
  build:
    when:
      event: push
    image: fhautomateddev/library-ci-tools
    pull: true
    auth_config:
      username: $$DOCKERHUB_USERNAME
      password: $$DOCKERHUB_PASSWORD
      email: $$DOCKERHUB_EMAIL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 /scripts/images/build.py
      
  spectests:
    when:
      event: push
    image: 1and1internet/ubuntu-16-rspec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export IMAGE=dronebuild$DRONE_BUILD_NUMBER/${CI_REPO#*/}
      - rspec -f documentation tests/serverspec.rb
      
  publish:
    when:
      branch: master
      event: push
    image: fhautomateddev/library-ci-tools
    auth_config:
     username: $$DOCKERHUB_USERNAME
     password: $$DOCKERHUB_PASSWORD
     email: $$DOCKERHUB_EMAIL
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /tmp/image-comparison:/tmp/image-comparison
    environment:
     - DOCKERHUB_USERNAME=$$DOCKERHUB_USERNAME
     - DOCKERHUB_EMAIL=$$DOCKERHUB_EMAIL
     - DOCKERHUB_PASSWORD=$$DOCKERHUB_PASSWORD
    commands:
     - bash /scripts/images/publish.sh