pipeline:

  tools:
    when:
      event: push
    image: docker
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
	  - docker --config /secrets/ pull 1and1internet/template-library-tools

  build:
    when:
      event: push
    image: fhautomateddev/library-ci-tools
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - python3 -u /scripts/images/build.py
      
  spectests:
    when:
      event: push
    image: 1and1internet/ubuntu-16-rspec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export IMAGE=build-${CI_REPO#*/}-${CI_BUILD_NUMBER}/${CI_REPO#*/}
      - echo ${IMAGE}
      - rspec -f documentation tests/serverspec.rb
      
  publish:
    when:
      event: push
    image: fhautomateddev/library-ci-tools
    volumes:
      - /secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
      - /shared_storage:/tmp/image-comparison
    commands:
     - python3 -u /scripts/images/publish.py
